export { LinkLeadPropertyUseCase } from './link-lead-property'
export type { LinkLeadPropertyInput } from './link-lead-property'
export { UpdateLeadPropertyStatusUseCase } from './update-lead-property-status'
export type { UpdateLeadPropertyStatusInput } from './update-lead-property-status'
export { UnlinkLeadPropertyUseCase } from './unlink-lead-property'
export type { UnlinkLeadPropertyInput } from './unlink-lead-property'
export { GetLeadPropertiesUseCase } from './get-lead-properties'
export type { GetLeadPropertiesInput } from './get-lead-properties'
export { GetPropertyInterestedLeadsUseCase } from './get-property-interested-leads'
export type { GetPropertyInterestedLeadsInput } from './get-property-interested-leads'
